#!groovy
@Library('jenkins-shared-library') _

properties([
  parameters([
    string(name: 'branchCheckout', defaultValue: 'master', description: 'Branch to Build'),    
   ])
])

def branchCheckout = params.branchCheckout

ecr_build_push_pipeline {
    branchCheckout  = branchCheckout
    region          = 'us-east-1'
    appRepo         = 'https://github.com/dvillarraga/CredentialRegistry.git'
    repoUri         = '815996728789.dkr.ecr.us-east-1.amazonaws.com'
    repoName        = 'credential-registry'
}