AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  AppTag:
    Type: String
    Default: 'credential-registry'

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join 
        - '-'
        - - "oscarv"
          - !Ref AppTag
  